#!/usr/bin/env python
"""Thesis tables: per-category LaTeX tables from the canonical run dirs.

Emits three booktabs tables (Ch 5 / Appendix A / Appendix B):
  thesis/tables/tab_percat_ucf.tex  -- UCF-Crime 13 categories, Gated Fusion
      SigLIP2-Giant (headline variant), 3-seed mean+/-std frame-level AUC (%).
  thesis/tables/tab_percat_xd.tex   -- XD-Violence 6 categories, Gated Fusion
      SigLIP2-SO400M (headline variant), 3-seed mean+/-std frame-level AP (%).
  thesis/tables/tab_percat_rtfm.tex -- RTFM-I3D XD baseline (RGB + Flow-swap
      diagnostic), per-category AP (%), SEED 42 ONLY (single-seed runs).

The per_category.csv files are the CURRENT post-lambda0 / post-h1 state and
are the ONLY valid per-category source. Phase-4/4c-era per-category values
are forbidden and never appear here (a self-check scans the emitted text for
the known stale literals and fails loudly if any slips in).

CPU-only. numpy / csv only. NO torch / CUDA. Deterministic (no stochastic
path; RNG seeded 12345 for policy compliance).

Data sources (read-only, ALL git-tracked):
  results/ucf_gated_fusion_giant_s{42,123,2024}/per_category.csv
  results/xd_gated_fusion_so400m_s{42,123,2024}/per_category.csv
  results/xd_i3d_rtfm_i3d_s42/per_category.csv
  results/xd_i3d_rtfm_i3d_flow_s42/per_category.csv
      (format: category,auc,ap -- one row per class, values on 0-1 scale)
"""
import csv
import os

import numpy as np

# ---- determinism (policy: seed every RNG with a fixed int) -------------------
_RNG = np.random.default_rng(12345)  # not used in any stochastic path

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(ROOT, "results")
OUT_DIR = os.path.join(ROOT, "thesis", "tables")
os.makedirs(OUT_DIR, exist_ok=True)

SEEDS = ("42", "123", "2024")

UCF_CATEGORIES = [
    "Abuse", "Arrest", "Arson", "Assault", "Burglary", "Explosion",
    "Fighting", "RoadAccidents", "Robbery", "Shooting", "Shoplifting",
    "Stealing", "Vandalism",
]
XD_CATEGORIES = ["B1", "B2", "B4", "B5", "B6", "G"]
XD_CAT_NAMES = {
    "B1": "Fighting", "B2": "Shooting", "B4": "Riot",
    "B5": "Abuse", "B6": "Car Accident", "G": "Explosion",
}

# Known Phase-4/4c-era stale per-category literals -- must never appear in the
# emitted tables (they can only come from hardcoding, which this script forbids).
FORBIDDEN_LITERALS = ("0.955", "0.985", "88.15", "44.89")


def _read_per_category(run_dir):
    """Read per_category.csv -> {category: {'auc': float, 'ap': float}}."""
    path = os.path.join(RESULTS, run_dir, "per_category.csv")
    out = {}
    with open(path, "r", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            out[row["category"]] = {
                "auc": float(row["auc"]), "ap": float(row["ap"])}
    return out


def _three_seed(run_base, categories, metric):
    """3-seed mean/std (ddof=0) per category, in percent."""
    per_seed = [_read_per_category(f"{run_base}_s{s}") for s in SEEDS]
    for d in per_seed:
        assert set(d.keys()) == set(categories), (
            f"{run_base}: category set mismatch: {sorted(d.keys())}")
    stats = {}
    for cat in categories:
        vals = np.array([d[cat][metric] for d in per_seed]) * 100.0
        stats[cat] = (float(np.mean(vals)), float(np.std(vals)))
    return stats


def _write_table(path, header_lines, caption, label, col_spec, col_header,
                 body_rows):
    lines = []
    lines.extend(header_lines)
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append(f"\\caption{{{caption}}}")
    lines.append(f"\\label{{{label}}}")
    lines.append(f"\\begin{{tabular}}{{{col_spec}}}")
    lines.append("\\toprule")
    lines.append(col_header + " \\\\")
    lines.append("\\midrule")
    lines.extend(r + " \\\\" for r in body_rows)
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    text = "\n".join(lines) + "\n"
    for lit in FORBIDDEN_LITERALS:
        assert lit not in text, (
            f"forbidden Phase-4/4c-era literal {lit!r} appeared in {path}")
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"[thesis_per_category_tables] wrote {path}")


def main():
    # ---- UCF: Gated Fusion Giant, 3-seed AUC ---------------------------------
    ucf = _three_seed("ucf_gated_fusion_giant", UCF_CATEGORIES, "auc")
    _write_table(
        os.path.join(OUT_DIR, "tab_percat_ucf.tex"),
        [
            "% Source: generated by scripts/thesis_per_category_tables.py"
            " (CPU-only, tracked).",
            "% Data: results/ucf_gated_fusion_giant_s{42,123,2024}/"
            "per_category.csv (tracked, post-lambda0/post-h1).",
            "% 3-seed mean+/-std, frame-level AUC (%).",
        ],
        "Per-category frame-level AUC (\\%) on UCF-Crime for the headline "
        "Gated Fusion variant (SigLIP2 Giant backbone). "
        "Mean$\\pm$std over three seeds (42, 123, 2024).",
        "tab:percat-ucf",
        "lr",
        "Category & AUC (\\%)",
        [f"{cat} & {m:.2f}$\\pm${s:.2f}"
         for cat, (m, s) in ((c, ucf[c]) for c in UCF_CATEGORIES)],
    )

    # ---- XD: Gated Fusion SO400M, 3-seed AP ----------------------------------
    xd = _three_seed("xd_gated_fusion_so400m", XD_CATEGORIES, "ap")
    _write_table(
        os.path.join(OUT_DIR, "tab_percat_xd.tex"),
        [
            "% Source: generated by scripts/thesis_per_category_tables.py"
            " (CPU-only, tracked).",
            "% Data: results/xd_gated_fusion_so400m_s{42,123,2024}/"
            "per_category.csv (tracked, post-lambda0/post-h1).",
            "% 3-seed mean+/-std, frame-level AP (%).",
        ],
        "Per-category frame-level AP (\\%) on XD-Violence for the headline "
        "Gated Fusion variant (SigLIP2 SO400M backbone). "
        "Mean$\\pm$std over three seeds (42, 123, 2024).",
        "tab:percat-xd",
        "llr",
        "Code & Category & AP (\\%)",
        [f"{cat} & {XD_CAT_NAMES[cat]} & {m:.2f}$\\pm${s:.2f}"
         for cat, (m, s) in ((c, xd[c]) for c in XD_CATEGORIES)],
    )

    # ---- RTFM: XD I3D baseline, s42 only (RGB + Flow-swap diagnostic) --------
    rgb = _read_per_category("xd_i3d_rtfm_i3d_s42")
    flow = _read_per_category("xd_i3d_rtfm_i3d_flow_s42")
    assert set(rgb.keys()) == set(XD_CATEGORIES), sorted(rgb.keys())
    assert set(flow.keys()) == set(XD_CATEGORIES), sorted(flow.keys())
    _write_table(
        os.path.join(OUT_DIR, "tab_percat_rtfm.tex"),
        [
            "% Source: generated by scripts/thesis_per_category_tables.py"
            " (CPU-only, tracked).",
            "% Data: results/xd_i3d_rtfm_i3d_s42/per_category.csv +",
            "%       results/xd_i3d_rtfm_i3d_flow_s42/per_category.csv"
            " (tracked).",
            "% SEED 42 ONLY -- the RTFM reproduction and its Flow-swap"
            " diagnostic are single-seed runs.",
        ],
        "Per-category frame-level AP (\\%) on XD-Violence for the RTFM-I3D "
        "reproduction (RGB features) and its Flow-swap diagnostic. "
        "Seed 42 only (single-seed runs).",
        "tab:percat-rtfm",
        "llrr",
        "Code & Category & RTFM (RGB) AP (\\%) & Flow-swap AP (\\%)",
        [f"{cat} & {XD_CAT_NAMES[cat]} & {rgb[cat]['ap'] * 100:.2f} & "
         f"{flow[cat]['ap'] * 100:.2f}"
         for cat in XD_CATEGORIES],
    )

    print("[thesis_per_category_tables] self-checks PASS "
          "(category sets exact; no Phase-4/4c-era literals in output)")


if __name__ == "__main__":
    main()
